{
    "type": "bundle",
    "id": "bundle--07f2656f-0bac-48b5-a4b6-4fc25370e961",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--bdd11ac5-739e-4299-a332-156ee4b9213c",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-07-01T09:22:35.654306Z",
            "modified": "2024-07-01T09:22:35.654306Z",
            "name": "CVE-2024-39428",
            "description": "In trusty service, there is a possible out of bounds write due to a missing bounds check. This could lead to local denial of service with System execution privileges needed",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-39428"
                }
            ]
        }
    ]
}