{
    "type": "bundle",
    "id": "bundle--a28d45a8-60c4-4687-9e8e-1acbdd835b50",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--bef26ae3-e139-4a73-b94a-646fcf082063",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-04-10T19:13:38.693466Z",
            "modified": "2024-04-10T19:13:38.693466Z",
            "name": "CVE-2024-30692",
            "description": "A issue was discovered in ROS2 Galactic Geochelone versions ROS_VERSION 2 and ROS_PYTHON_VERSION 3, allows remote attackers to cause a denial of service (DoS) in the ROS2 nodes.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-30692"
                }
            ]
        }
    ]
}