{
    "type": "bundle",
    "id": "bundle--ca128a95-86a2-4870-ba15-2c45bbbb2231",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--3aeb006d-ac43-44fe-b452-bb094b59b9ce",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-06-19T15:18:56.384553Z",
            "modified": "2024-06-19T15:18:56.384553Z",
            "name": "CVE-2021-47616",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nRDMA: Fix use-after-free in rxe_queue_cleanup\n\nOn error handling path in rxe_qp_from_init() qp->sq.queue is freed and\nthen rxe_create_qp() will drop last reference to this object. qp clean up\nfunction will try to free this queue one time and it causes UAF bug.\n\nFix it by zeroing queue pointer after freeing queue in rxe_qp_from_init().",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2021-47616"
                }
            ]
        }
    ]
}