{
    "id": "bundle--57d2a71d-e3e8-439b-a955-f8000a369b85",
    "objects": [
        {
            "created": "2021-03-13T20:11:49.061369Z",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "description": "django-js-reverse (aka Django JS Reverse) before 0.9.1 has XSS via js_reverse_inline.",
            "external_references": [
                {
                    "external_id": "CVE-2019-15486",
                    "source_name": "cve"
                }
            ],
            "id": "vulnerability--75a503b0-aa8c-4ff2-b206-6a8b76a1d648",
            "modified": "2021-11-22T14:54:52.900149Z",
            "name": "CVE-2019-15486",
            "spec_version": "2.1",
            "type": "vulnerability"
        }
    ],
    "type": "bundle"
}