{
    "id": "bundle--2038c223-28c4-4eab-b452-872846afd51d",
    "objects": [
        {
            "created": "2021-03-13T20:12:59.595356Z",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "description": "An issue was discovered in the Linux kernel before 4.19.9. The USB subsystem mishandles size checks during the reading of an extra descriptor, related to __usb_get_extra_descriptor in drivers/usb/core/usb.c.",
            "external_references": [
                {
                    "external_id": "CVE-2018-20169",
                    "source_name": "cve"
                }
            ],
            "id": "vulnerability--e1273d74-31ee-4456-9330-1e1644f89be2",
            "modified": "2021-12-01T16:19:51.601791Z",
            "name": "CVE-2018-20169",
            "spec_version": "2.1",
            "type": "vulnerability"
        }
    ],
    "type": "bundle"
}