{
    "type": "bundle",
    "id": "bundle--93071d03-0a66-447e-a002-7b00ee20c59e",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--52ca9bb8-f687-480d-a320-50361b93cc88",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-01-31T00:25:11.11981Z",
            "modified": "2022-01-31T00:25:11.11981Z",
            "name": "CVE-2022-0413",
            "description": "Use After Free in Conda vim prior to 8.2.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-0413"
                }
            ]
        }
    ]
}