{
    "type": "bundle",
    "id": "bundle--60ae84ba-9d94-4620-8beb-ae7a442e86ed",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--16cea1ec-9f4c-4e51-a21d-45aa2f35064a",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-12-16T00:05:27.140172Z",
            "modified": "2022-12-16T00:05:27.140172Z",
            "name": "CVE-2022-42849",
            "description": "An access issue existed with privileged API calls. This issue was addressed with additional restrictions. This issue is fixed in iOS 16.2 and iPadOS 16.2, tvOS 16.2, watchOS 9.2. A user may be able to elevate privileges.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-42849"
                }
            ]
        }
    ]
}