{
    "id": "bundle--ac9b9d95-d958-4cc1-b57d-fc845b87c90d",
    "objects": [
        {
            "created": "2021-03-13T20:10:08.72647Z",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "description": "software-properties was vulnerable to a person-in-the-middle attack due to incorrect TLS certificate validation in softwareproperties/ppa.py. software-properties didn't check TLS certificates under python2 and only checked certificates under python3 if a valid certificate bundle was provided. Fixed in software-properties version 0.92.",
            "external_references": [
                {
                    "external_id": "CVE-2012-0955",
                    "source_name": "cve"
                }
            ],
            "id": "vulnerability--3fb5a268-02bb-4407-8bd1-499765f17002",
            "modified": "2021-11-22T14:54:52.900149Z",
            "name": "CVE-2012-0955",
            "spec_version": "2.1",
            "type": "vulnerability"
        }
    ],
    "type": "bundle"
}