{
    "id": "bundle--bdb5f6f1-8083-4e9c-b4c8-101785fbfbae",
    "objects": [
        {
            "created": "2021-03-13T20:11:59.106915Z",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "description": "An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP.",
            "external_references": [
                {
                    "external_id": "CVE-2019-12781",
                    "source_name": "cve"
                }
            ],
            "id": "vulnerability--0816399c-7880-46d2-ad66-3bf6d09d0441",
            "modified": "2021-11-22T14:54:52.900149Z",
            "name": "CVE-2019-12781",
            "spec_version": "2.1",
            "type": "vulnerability"
        }
    ],
    "type": "bundle"
}