{
    "type": "bundle",
    "id": "bundle--da83d66c-c24e-464b-aa23-e8230d55c6aa",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--1a4bfd67-940b-434c-a6a5-46ea2d7744b9",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-01-18T00:05:21.216017Z",
            "modified": "2023-01-18T00:05:21.216017Z",
            "name": "CVE-2022-46732",
            "description": "Even if the authentication fails for local service authentication, the requested command could still execute regardless of authentication status.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-46732"
                }
            ]
        }
    ]
}