{
    "type": "bundle",
    "id": "bundle--8ed12cdb-1f81-4adb-bd0e-42c1c71788ab",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--d9ccb60a-d15e-4639-9aa0-3f12595105c7",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-08-19T00:06:51.171101Z",
            "modified": "2022-08-19T00:06:51.171101Z",
            "name": "CVE-2020-36599",
            "description": "lib/omniauth/failure_endpoint.rb in OmniAuth before 2.0 does not escape the message_key value.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-36599"
                }
            ]
        }
    ]
}