{
    "id": "bundle--df6ea470-9423-4a9b-8cd0-a3016e59f16a",
    "objects": [
        {
            "created": "2021-03-13T20:12:41.017126Z",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "description": "dhowden tag before 2020-11-19 allows \"panic: runtime error: index out of range\" via readAPICFrame.",
            "external_references": [
                {
                    "external_id": "CVE-2020-29243",
                    "source_name": "cve"
                }
            ],
            "id": "vulnerability--e7fc4e47-5629-4d48-b547-d9a32a9b17ee",
            "modified": "2021-11-22T14:54:52.900149Z",
            "name": "CVE-2020-29243",
            "spec_version": "2.1",
            "type": "vulnerability"
        }
    ],
    "type": "bundle"
}